// frontend/src/components/shared/Navbar.jsx
import React, { useState, useEffect } from 'react';
import { Link, useLocation } from 'react-router-dom';

const Navbar = () => {
    const [scrolled, setScrolled] = useState(false);
    const [hidden, setHidden] = useState(false);
    const [menuOpen, setMenuOpen] = useState(false);
    const [lastScrollY, setLastScrollY] = useState(0);
    const location = useLocation();

    useEffect(() => {
        const handleScroll = () => {
            const currentScrollY = window.scrollY;

            if (currentScrollY > 50) {
                setScrolled(true);
            } else {
                setScrolled(false);
            }

            if (currentScrollY > lastScrollY && currentScrollY > 200) {
                setHidden(true);
            } else {
                setHidden(false);
            }

            setLastScrollY(currentScrollY);
        };

        window.addEventListener('scroll', handleScroll, { passive: true });
        return () => window.removeEventListener('scroll', handleScroll);
    }, [lastScrollY]);

    const toggleMenu = () => setMenuOpen(!menuOpen);

    return (
        <nav
            className={`main-nav ${scrolled ? 'scrolled' : ''}`}
            id="navbar"
            style={{ transform: hidden ? 'translateY(-100%)' : 'translateY(0)' }}
        >
            <div className="nav-container">
                <Link to="/" className="logo">
                    <img src="/assets/images/ethiroli_logo.png" alt="Ethiroli Logo" />
                </Link>
                <ul className="nav-links">
                    <li><Link to="/">Home</Link></li>
                    <li><Link to="/about" className={location.pathname === '/about' ? 'active' : ''}>About Us</Link></li>
                    <li><Link to="/services" className={location.pathname === '/services' ? 'active' : ''}>Services</Link></li>
                    <li><Link to="/projects" className={location.pathname.startsWith('/projects') ? 'active' : ''}>Project</Link></li>
                    <li><Link to="/career" className={location.pathname === '/career' ? 'active' : ''}>Career</Link></li>
                    <li><Link to="/contact_us" className={location.pathname === '/contact_us' ? 'active' : ''}>Contact</Link></li>
                </ul>
                <div className="nav-actions">
                    <Link to="/contact_us" className="btn">Get in Touch</Link>
                    <button
                        className={`hamburger ${menuOpen ? 'open' : ''}`}
                        id="hamburger-btn"
                        aria-label="Menu"
                        aria-expanded={menuOpen}
                        onClick={toggleMenu}
                    >
                        <span></span>
                        <span></span>
                        <span></span>
                    </button>
                </div>
            </div>

            <div className={`mobile-menu ${menuOpen ? 'active' : ''}`} id="mobile-menu">
                <ul>
                    <li><Link to="/" className="mobile-link" onClick={() => setMenuOpen(false)}>Home</Link></li>
                    <li><Link to="/about" className="mobile-link" onClick={() => setMenuOpen(false)}>About Us</Link></li>
                    <li><Link to="/services" className="mobile-link" onClick={() => setMenuOpen(false)}>Services</Link></li>
                    <li><Link to="/projects" className="mobile-link" onClick={() => setMenuOpen(false)}>Project</Link></li>
                    <li><Link to="/career" className="mobile-link" onClick={() => setMenuOpen(false)}>Career</Link></li>
                    <li><Link to="/contact_us" className="mobile-link" onClick={() => setMenuOpen(false)}>Contact</Link></li>
                </ul>
                <Link to="/contact_us" className="btn" onClick={() => setMenuOpen(false)}>Get in Touch</Link>
            </div>
        </nav>
        
    );
};

export default Navbar;

// ethiroli-vue/src/components/shared/Navbar.vue
<script setup>
import { ref, onMounted, onUnmounted, watch } from 'vue'
import { useRoute } from 'vue-router'

const route = useRoute()
const scrolled = ref(false)
const hidden = ref(false)
const menuOpen = ref(false)
let lastScrollY = 0

const toggleMenu = () => {
  menuOpen.value = !menuOpen.value
}

const handleScroll = () => {
  const currentScrollY = window.scrollY

  scrolled.value = currentScrollY > 50
  
  if (currentScrollY > lastScrollY && currentScrollY > 200) {
    hidden.value = true
  } else {
    hidden.value = false
  }

  lastScrollY = currentScrollY
}

onMounted(() => {
  window.addEventListener('scroll', handleScroll, { passive: true })
})

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll)
})

watch(() => route.fullPath, () => {
  menuOpen.value = false
})
</script>

<template>
  <nav 
    class="main-nav" 
    :class="{ 'scrolled': scrolled }" 
    :style="{ transform: hidden ? 'translateY(-100%)' : 'translateY(0)' }"
  >
    <div class="nav-container">
      <router-link to="/" class="logo">
        <img src="/assets/images/ethiroli_logo.png" alt="Ethiroli Logo" />
      </router-link>
      <ul class="nav-links">
        <li><router-link to="/">Home</router-link></li>
        <li><a href="/#services">Services</a></li>
        <li><router-link to="/about" active-class="active">About Us</router-link></li>
        <li><router-link to="/career" active-class="active">Career</router-link></li>
        <li><router-link to="/contact_us" active-class="active">Contact</router-link></li>
      </ul>
      <div class="nav-actions">
        <router-link to="/contact_us" class="btn">Get in Touch</router-link>
        <button 
          class="hamburger" 
          :class="{ 'open': menuOpen }" 
          aria-label="Menu" 
          :aria-expanded="menuOpen"
          @click="toggleMenu"
        >
          <span></span>
          <span></span>
          <span></span>
        </button>
      </div>
    </div>
    
    <div class="mobile-menu" :class="{ 'active': menuOpen }">
      <ul>
        <li><router-link to="/" class="mobile-link">Home</router-link></li>
        <li><a href="/#services" class="mobile-link" @click="menuOpen = false">Services</a></li>
        <li><router-link to="/about" class="mobile-link">About Us</router-link></li>
        <li><router-link to="/career" class="mobile-link">Career</router-link></li>
        <li><router-link to="/contact_us" class="mobile-link">Contact</router-link></li>
      </ul>
      <router-link to="/contact_us" class="btn" @click="menuOpen = false">Get in Touch</router-link>
    </div>
  </nav>
</template>
