// ethiroli-vue/src/components/home/Hero.vue
<script setup>
// For Intersection Observer-based enter animations (scroll reveals)
import { ref, onMounted, onUnmounted } from 'vue'

const isVisibleP = ref(false)
const isVisibleH1 = ref(false)

onMounted(() => {
    // Slight delay for load-in effect matching Framer Motion's initial mount
    setTimeout(() => {
        isVisibleP.value = true
    }, 500)
    
    setTimeout(() => {
        isVisibleH1.value = true
    }, 1000)
})
</script>

<template>
    <header>
        <div class="et-hero-section">
            <video 
                autoplay 
                muted 
                loop 
                playsinline 
                poster="/assets/images/ethiroli_video_poster.jpg" 
                class="bg-video"
            >
                <source src="/assets/images/ethiroli.mp4" type="video/mp4" />
                <source src="/assets/images/ethiroli.webm" type="video/webm" />
            </video>
            <div class="video-overlay"></div>
            <div class="video-content">
                <transition name="fade-up">
                    <p v-show="isVisibleP">BRANDING</p>
                </transition>
                <transition name="fade-up">
                    <h1 v-show="isVisibleH1">MARKETING</h1>
                </transition>
            </div>
        </div>
    </header>
</template>

<style scoped>
/* Scoped transitions mapping to native enter-from states */
.fade-up-enter-active,
.fade-up-leave-active {
  transition: all 1s ease;
}

.fade-up-enter-from,
.fade-up-leave-to {
  opacity: 0;
  transform: translateY(30px);
}
</style>

// ethiroli-react/frontend/src/app/marketing/components/home/Hero.jsx
import React from 'react';
import { motion } from 'framer-motion';

const Hero = () => {
    return (
        <header>
            <div className="et-hero-section">
                <video
                    autoPlay
                    muted
                    loop
                    playsInline
                    poster="/assets/images/ethiroli_video_poster.jpg"
                    className="bg-video"
                >
                    <source src="/assets/images/ethiroli.mp4" type="video/mp4" />
                    <source src="/assets/images/ethiroli.webm" type="video/webm" />
                </video>
                <div className="video-overlay"></div>
                <div className="video-content">
                    <motion.p
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 1, delay: 0.5 }}
                    >
                        BRANDING
                    </motion.p>
                    <motion.h1
                        initial={{ opacity: 0, y: 30 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 1, delay: 1 }}
                    >
                        MARKETING
                    </motion.h1>
                </div>
            </div>
        </header>
    );
};

export default Hero;
